SQLITE_DB_FILE = "db.sqlite3"
DATE_FORMAT = "%d.%m.%Y"
VOTE_ELEMENTS_COUNT = 3
CATEGORIES_PER_BOARD = 5

ALL_BOOKS_CALLBACK_PATTERN = "all_books_"
VOTE_BOOKS_CALLBACK_PATTERN = "vote_"
CATEGORIES_LIST_CALLBACK_PATTERN = "categories_"
SELECT_CATEGORY_PATTERN = "select_category_"
