SQLITE_DB_FILE = "db.sqlite3"
DATE_FORMAT = "%d.%m.%Y"
VOTE_ELEMENTS_COUNT = 3
SLEEP_BETWEEN_MESSAGES_TO_ONE_USER = 0.3

ALL_BOOKS_CALLBACK_PATTERN = "all_books_"
VOTE_BOOKS_CALLBACK_PATTERN = "vote_"
